<?php
/*
 * Generic functions in theme
 */
define( 'W_TEMPLATE_URL', get_stylesheet_directory_uri() );
define( 'W_TEMPLATE_DIRECTORY', get_stylesheet_directory() );

function w_get_stylesheet_uri()
{
	return get_stylesheet_uri() . '?v=' . filemtime( W_TEMPLATE_DIRECTORY . '/style.css' );
}

function w_the_page_title()
{
	global $page, $paged;

	wp_title( '|', true, 'right' );

	// Add the blog name.
	bloginfo( 'name' );

	// Add the blog description for the home/front page.
	$site_description = get_bloginfo( 'description', 'display' );
	if ( $site_description && ( is_home() || is_front_page() ) )
		printf( ' | %s', $site_description );

	// Add a page number if necessary:
	if ( $paged >= 2 || $page >= 2 )
		echo ' | ' . sprintf( 'Página %s', max( $paged, $page ) );
}

function w_remove_meta_tags()
{
	// All meta tags generated by WordPress	
	$meta_tags = array(
		'wp_generator',
		'feed_links',
		'feed_links_extra',
		'rsd_link',
		'wlwmanifest_link',
		'index_rel_link',
		'parent_post_rel_link',
		'start_post_rel_link',
		'adjacent_posts_rel_link_wp_head',
		'wp_shortlink_wp_head',
	);

	// Remove the meta tag generator from all resources, head, rss, etc
	if ( isset( $meta_tags['wp_generator'] ) )
		add_action( 'the_generator', '__return_false' );

	// An array with the same size of the $meta_tags to pass by in array_map
	$arr_hook = array_fill( 0, count( $meta_tags ), 'wp_head' );

	// Remove all tags contains in $meta_tags
	array_map( 'remove_action', $arr_hook, $meta_tags );
}

function w_the_image( $name )
{
	echo W_TEMPLATE_URL . "/assets/images/{$name}";
}

function w_site_enqueue_script()
{
	wp_enqueue_script(
		'resuta-front',
		W_TEMPLATE_URL . '/assets/javascripts/built.js',
		null,
		filemtime( W_TEMPLATE_DIRECTORY . '/assets/javascripts/built.js' ),
		true
	);

	wp_localize_script(
		'resuta-front', 
		'SiteGlobalVars',
		array(
			'urlAjax' => admin_url( 'admin-ajax.php' ),
		)
	);
}

/*
 * After setuo theme action
 * Remove defauls meta tags, generator and show admin bar
 */
function w_after_setup_theme()
{
	w_remove_meta_tags();
	add_action( 'show_admin_bar', '__return_false' );

	//hooks scripts
	add_action( 'wp_enqueue_scripts', 'w_site_enqueue_script' );
}

add_action( 'after_setup_theme', 'w_after_setup_theme' );